import {
  School as GraduationCapIcon,
  Dashboard as LayoutDashboardIcon,
  Description as FileTextIcon,
  BarChart as BarChartIcon,
  People as PeopleIcon,
  Person as PersonIcon,
  Add as AddIcon,
  Notifications as NotificationsIcon,
  Chat as MessageSquareIcon,
  Feedback as FeedbackIcon,
  Assignment as AssignmentIcon,
  CheckCircle as CheckCircleIcon,
  Cancel as CancelIcon,
  Schedule as ScheduleIcon,
  Warning as WarningIcon,
  Visibility as VisibilityIcon,
  VisibilityOff as VisibilityOffIcon,
  Search as SearchIcon,
  Logout as LogOutIcon,
  ManageAccounts as ManageAccountsIcon,
  Lock as LockIcon,
  LockOpen as LockOpenIcon,
  Edit as EditIcon,
  Delete as DeleteIcon,
  AddCircle as AddCircleIcon,
  Folder as FolderIcon,
  Flag as FlagIcon,
  Groups as GroupsIcon,
  GroupAdd as GroupAddIcon,
  GroupRemove as GroupRemoveIcon,
  CalendarMonth as CalendarIcon,
  CalendarToday as CalendarTodayIcon,
  AccessTime as ClockIcon,
  Send as SendIcon,
  Download as DownloadIcon,
  Upload as UploadIcon,
  Summarize as SummarizeIcon,
  FlashOn as SparklesIcon,
  OpenInNew as OpenInNewIcon,
  ArrowBack as ArrowBackIcon,
  Star as StarIcon,
  Email as EmailIcon,
  Phone as PhoneIcon,
  VerifiedUser as VerifiedUserIcon,
  Gavel as GavelIcon,
  Settings as SettingsIcon,
  Dashboard as DashboardIcon,
  FactCheck as FactCheckIcon,
  RateReview as RateReviewIcon,
  HowToReg as HowToRegIcon,
  RateReview as ReviewIcon,
  ListAlt as ListAltIcon,
  FilterList as FilterListIcon,
  MarkEmailRead as MarkEmailReadIcon,
  Markunread as MarkUnreadIcon,
  CheckBox as CheckBoxIcon,
  CheckBoxOutlineBlank as CheckBoxOutlineBlankIcon,
  ThumbUp as ThumbUpIcon,
  ThumbDown as ThumbDownIcon,
  Refresh as RefreshIcon,
  Close as CloseIcon,
  MoreVert as MoreVertIcon,
  Sort as SortIcon,
  AccountCircle as AccountCircleIcon,
  PersonPin as PersonPinIcon,
  SupervisorAccount as SupervisorAccountIcon,
  AdminPanelSettings as AdminIcon,
  Science as ScienceIcon,
  Terminal as TerminalIcon,
  NoteAlt as NoteAltIcon,
  Quiz as QuizIcon,
  Lightbulb as LightbulbIcon,
  School as SchoolIcon,
  ExpandMore as ExpandIcon,
  Error as ErrorIcon,
  Videocam as VideoIcon,
  Place as MapPinIcon,
  CloudUpload as CloudUploadIcon,
  Save as SaveIcon,
  ManageAccounts as UserCogIcon,
} from "@mui/icons-material";
import { SvgIcon } from "@mui/material";

const ICON_MAP = {
  GraduationCap: GraduationCapIcon,
  LayoutDashboard: LayoutDashboardIcon,
  FileText: FileTextIcon,
  BarChart: BarChartIcon,
  People: PeopleIcon,
  Users: PeopleIcon,
  Person: PersonIcon,
  User: PersonIcon,
  Add: AddIcon,
  Plus: AddIcon,
  Bell: NotificationsIcon,
  Notifications: NotificationsIcon,
  MessageSquare: MessageSquareIcon,
  Chat: MessageSquareIcon,
  Feedback: FeedbackIcon,
  Assignment: AssignmentIcon,
  CheckCircle: CheckCircleIcon,
  CheckCircleFilled: CheckCircleIcon,
  Cancel: CancelIcon,
  XCircle: CancelIcon,
  Close: CloseIcon,
  Clock: ClockIcon,
  Schedule: ScheduleIcon,
  AlertTriangle: WarningIcon,
  Warning: WarningIcon,
  Eye: VisibilityIcon,
  Visibility: VisibilityIcon,
  VisibilityOff: VisibilityOffIcon,
  Search: SearchIcon,
  LogOut: LogOutIcon,
  Logout: LogOutIcon,
  Lock: LockIcon,
  Unlock: LockOpenIcon,
  Edit: EditIcon,
  Pencil: EditIcon,
  Delete: DeleteIcon,
  Trash: DeleteIcon,
  Folder: FolderIcon,
  FolderKanban: FolderIcon,
  Flag: FlagIcon,
  Groups: GroupsIcon,
  GroupAdd: GroupAddIcon,
  GroupRemove: GroupRemoveIcon,
  Calendar: CalendarIcon,
  CalendarToday: CalendarTodayIcon,
  Send: SendIcon,
  Download: DownloadIcon,
  Upload: UploadIcon,
  Summarize: SummarizeIcon,
  Sparkles: SparklesIcon,
  FlashOn: SparklesIcon,
  OpenInNew: OpenInNewIcon,
  ArrowBack: ArrowBackIcon,
  ArrowLeft: ArrowBackIcon,
  Star: StarIcon,
  Email: EmailIcon,
  Mail: EmailIcon,
  Phone: PhoneIcon,
  VerifiedUser: VerifiedUserIcon,
  Gavel: GavelIcon,
  Settings: SettingsIcon,
  Dashboard: DashboardIcon,
  FactCheck: FactCheckIcon,
  RateReview: RateReviewIcon,
  HowToReg: HowToRegIcon,
  Review: ReviewIcon,
  ListAlt: ListAltIcon,
  FilterList: FilterListIcon,
  MarkEmailRead: MarkEmailReadIcon,
  MarkUnread: MarkUnreadIcon,
  CheckBox: CheckBoxIcon,
  CheckBoxOutlineBlank: CheckBoxOutlineBlankIcon,
  ThumbUp: ThumbUpIcon,
  ThumbDown: ThumbDownIcon,
  Refresh: RefreshIcon,
  MoreVert: MoreVertIcon,
  Sort: SortIcon,
  AccountCircle: AccountCircleIcon,
  PersonPin: PersonPinIcon,
  SupervisorAccount: SupervisorAccountIcon,
  AdminPanelSettings: AdminIcon,
  Science: ScienceIcon,
  Terminal: TerminalIcon,
  NoteAlt: NoteAltIcon,
  Quiz: QuizIcon,
  Lightbulb: LightbulbIcon,
  School: SchoolIcon,
  Expand: ExpandIcon,
  Error: ErrorIcon,
  AlertCircle: ErrorIcon,
  Video: VideoIcon,
  MapPin: MapPinIcon,
  UploadCloud: CloudUploadIcon,
  Save: SaveIcon,
  UserCog: UserCogIcon,
};

const FallbackIcon = ({ size = 20 }) => (
  <SvgIcon sx={{ width: size, height: size }}>
    <circle cx="12" cy="12" r="10" fill="currentColor" opacity="0.3" />
    <text x="12" y="16" textAnchor="middle" fontSize="10" fill="currentColor">?</text>
  </SvgIcon>
);

export default function Icon({ name, size = 20, color, className, sx, ...props }) {
  const IconComponent = ICON_MAP[name] || ICON_MAP[name.replace(/([A-Z])/g, (m) => m.toLowerCase())];
  if (!IconComponent) return <FallbackIcon size={size} />;
  return <IconComponent sx={{ width: size, height: size, color, ...sx }} {...props} />;
}

export {
  GraduationCapIcon, LayoutDashboardIcon, FileTextIcon, BarChartIcon,
  PeopleIcon, PersonIcon, AddIcon, NotificationsIcon, MessageSquareIcon,
  FeedbackIcon, AssignmentIcon, CheckCircleIcon, CancelIcon, ClockIcon,
  WarningIcon, VisibilityIcon, VisibilityOffIcon, SearchIcon, LogOutIcon,
  LockIcon, LockOpenIcon, EditIcon, DeleteIcon, FolderIcon, FlagIcon,
  GroupsIcon, GroupAddIcon, CalendarIcon, CalendarTodayIcon, SendIcon,
  DownloadIcon, UploadIcon, SparklesIcon, ArrowBackIcon, StarIcon,
  EmailIcon, PhoneIcon, VerifiedUserIcon, GavelIcon, SettingsIcon,
  DashboardIcon, FactCheckIcon, HowToRegIcon, ReviewIcon, ListAltIcon,
  FilterListIcon, MarkEmailReadIcon, CheckBoxIcon, ThumbUpIcon,
  ThumbDownIcon, RefreshIcon, CloseIcon, MoreVertIcon, SortIcon,
  AccountCircleIcon, PersonPinIcon, SupervisorAccountIcon, AdminIcon,
  ScienceIcon, TerminalIcon, NoteAltIcon, QuizIcon, LightbulbIcon, SchoolIcon,
  ExpandIcon, ErrorIcon, VideoIcon, MapPinIcon, CloudUploadIcon, SaveIcon, UserCogIcon,
};
